import mongoose from "mongoose";

const notificationSchema = new mongoose.Schema(
  {
    userId: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: "User", 
      required: true 
    },
    title: { 
      type: String, 
      required: true,
      trim: true,
      maxlength: 200
    },
    message: { 
      type: String, 
      required: true,
      trim: true,
      maxlength: 1000
    },
    type: { 
      type: String, 
      enum: [
        "info",           // معلومات عامة
        "warning",        // تحذير
        "success",        // نجاح عملية
        "error",          // خطأ
        "system",         // إشعار نظام
        "subscription",   // متعلق بالاشتراك
        "security",       // أمان
        "login",          // تسجيل دخول
        "payment",        // دفع
        "limit",          // حدود الاستخدام
        "welcome",        // ترحيب
        "reminder"        // تذكير
      ], 
      required: true,
      default: "info"
    },
    priority: {
      type: String,
      enum: ["low", "medium", "high", "urgent"],
      default: "medium"
    },
    category: {
      type: String,
      enum: [
        "account",        // حساب المستخدم
        "subscription",   // الاشتراك
        "security",       // الأمان
        "system",         // النظام
        "billing",        // الفواتير
        "general"         // عام
      ],
      default: "general"
    },
    isRead: { 
      type: Boolean, 
      default: false 
    },
    readAt: { 
      type: Date, 
      default: null 
    },
    isArchived: {
      type: Boolean,
      default: false
    },
    archivedAt: {
      type: Date,
      default: null
    },
    // للإشعارات التلقائية
    isAutoGenerated: {
      type: Boolean,
      default: false
    },
    autoType: {
      type: String,
      enum: [
        "subscription_expiry_warning",  // تحذير انتهاء الاشتراك
        "subscription_expired",         // انتهى الاشتراك
        "subscription_activated",       // تم تفعيل الاشتراك
        "limit_warning",               // تحذير الحدود
        "limit_exceeded",              // تجاوز الحدود
        "login_alert",                 // تنبيه تسجيل دخول
        "security_alert",              // تنبيه أمني
        "welcome_message",             // رسالة ترحيب
        "payment_received",            // تم استلام الدفع
        "account_suspended",           // تم إيقاف الحساب
        "account_reactivated"          // تم إعادة تفعيل الحساب
      ],
      required: false
    },
    // بيانات إضافية محسنة
    metadata: {
      transactionId: { type: String },
      paymentMethod: { type: String },
      amount: { type: Number },
      ipAddress: { type: String },
      userAgent: { type: String },
      location: { type: String },
      device: { type: String },
      daysLeft: { type: Number },
      limitType: { type: String },
      current: { type: Number },
      limit: { type: Number },
      percentage: { type: Number }
    },
    // للإشعارات المجدولة
    scheduledFor: {
      type: Date,
      default: null
    },
    isSent: {
      type: Boolean,
      default: true
    },
    sentAt: {
      type: Date,
      default: Date.now
    },
    // معرف الإشعار المرجعي (للتحديثات)
    referenceId: {
      type: String,
      required: false
    },
    // انتهاء صلاحية الإشعار
    expiresAt: {
      type: Date,
      default: null
    },
    // للتوافق مع الكود الموجود
    isHandled: { type: Boolean, default: false }
  },
  { 
    timestamps: true,
    // فهرسة للأداء
    indexes: [
      { userId: 1, createdAt: -1 },
      { userId: 1, isRead: 1 },
      { type: 1, createdAt: -1 },
      { priority: 1, createdAt: -1 },
      { scheduledFor: 1, isSent: 1 },
      { expiresAt: 1 },
      { autoType: 1, userId: 1 }
    ]
  }
);

// Methods للإشعارات
notificationSchema.methods.markAsRead = async function() {
  this.isRead = true;
  this.readAt = new Date();
  return await this.save();
};

notificationSchema.methods.archive = async function() {
  this.isArchived = true;
  this.archivedAt = new Date();
  return await this.save();
};

notificationSchema.methods.isExpired = function() {
  return this.expiresAt && new Date() > this.expiresAt;
};

// Static methods
notificationSchema.statics.getUnreadCount = async function(userId) {
  return await this.countDocuments({
    userId: userId,
    isRead: false,
    isArchived: false,
    $or: [
      { expiresAt: null },
      { expiresAt: { $gt: new Date() } }
    ]
  });
};

notificationSchema.statics.markAllAsRead = async function(userId) {
  return await this.updateMany(
    { 
      userId: userId, 
      isRead: false,
      isArchived: false 
    },
    { 
      isRead: true, 
      readAt: new Date() 
    }
  );
};

notificationSchema.statics.cleanupExpired = async function() {
  return await this.deleteMany({
    expiresAt: { $lt: new Date() }
  });
};

// إنشاء إشعار تلقائي
notificationSchema.statics.createAutoNotification = async function(userId, autoType, data = {}) {
  const templates = {
    subscription_expiry_warning: {
      title: "تحذير: اشتراكك ينتهي قريباً",
      message: `اشتراكك سينتهي في ${data.daysLeft} أيام. يرجى التجديد لتجنب انقطاع الخدمة.`,
      type: "warning",
      priority: "high",
      category: "subscription"
    },
    subscription_expired: {
      title: "انتهى اشتراكك",
      message: "انتهت صلاحية اشتراكك. يرجى التجديد لاستكمال استخدام الخدمة.",
      type: "error",
      priority: "urgent",
      category: "subscription"
    },
    subscription_activated: {
      title: "تم تفعيل اشتراكك",
      message: `تم تفعيل اشتراكك بنجاح. خطة: ${data.plan}، صالح حتى: ${data.endDate}`,
      type: "success",
      priority: "high",
      category: "subscription"
    },
    limit_warning: {
      title: `تحذير: اقتربت من حد ${data.limitType}`,
      message: `لقد استخدمت ${data.percentage}% من حد ${data.limitType} المسموح (${data.current}/${data.limit})`,
      type: "warning",
      priority: "medium",
      category: "account"
    },
    limit_exceeded: {
      title: `تم تجاوز حد ${data.limitType}`,
      message: `لقد تجاوزت الحد المسموح لـ ${data.limitType}. يرجى ترقية خطتك أو الانتظار حتى التجديد.`,
      type: "error",
      priority: "high",
      category: "account"
    },
    login_alert: {
      title: "تسجيل دخول جديد",
      message: `تم تسجيل دخول جديد لحسابك من ${data.location} باستخدام ${data.device}`,
      type: "security",
      priority: "medium",
      category: "security"
    },
    welcome_message: {
      title: "مرحباً بك في منصة نقطة",
      message: "نرحب بك في منصتنا. يمكنك الآن البدء في استخدام جميع الميزات المتاحة.",
      type: "welcome",
      priority: "medium",
      category: "account"
    }
  };

  const template = templates[autoType];
  if (!template) {
    throw new Error(`Unknown auto notification type: ${autoType}`);
  }

  return await this.create({
    userId,
    ...template,
    isAutoGenerated: true,
    autoType,
    metadata: data
  });
};

const Notification = mongoose.models.Notification || mongoose.model("Notification", notificationSchema);

// تصدير النموذج
export default Notification;